[package]
name = "s4n"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
colored = "2.1.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_yml = "0.0.12"
serde_json = "1.0.132"
fancy-regex = "0.11.0"
pathdiff = "0.2.1"
rand = "0.8.5"
sha1 = "0.10.6"
serial_test = "3.1.1"
syntect = { version = "5.2.0", default-features = false, features = [
    "regex-fancy",
    "parsing",
    "default-themes",
    "default-syntaxes",
] }
sysinfo = "0.32.0"
tempfile = "3.13.0"
urlencoding = "2.1.3"

[dependencies]
cwl = { path = "./crates/lib-cwl" }
s4n-core = { path = "./crates/lib-core" }
colored = { workspace = true }
serde_yml = { workspace = true }
clap = { version = "4.5.18", features = ["derive", "wrap_help"] }
git2 = { version = "0.19.0", features = ["vendored-openssl"] }
rust_xlsxwriter = "0.78.0"
shlex = "1.3.0"
slugify = "0.1.0"
walkdir = "2.5.0"
prettytable-rs = "0.10.0"
whoami = "1.5.2"

[dev-dependencies]
calamine = "0.25.0"
assert_cmd = "2.0.16"
predicates = "3.1.2"
tempfile = { workspace = true }
serial_test = { workspace = true }
