name: 🦀 Continuous Integration

on:
  push:
    branches: ["main", "feature/**"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_checks:
    name: 📎 Clippy
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: ./.github/workflows/clippy.yml
  build:
    name: 🏗️ Build and Test    
    uses: ./.github/workflows/build.yml    
  coverage:
    name: 🦺 Coverage
    permissions:
      contents: read
      pull-requests: write
      actions: read
    uses: ./.github/workflows/tarpaulin.yml    
  nightly:
    name: 🕶️ Nightly Release
    if: github.event_name == 'push' && github.action_ref == 'refs/heads/main'
    uses: ./.github/workflows/nightly.yml