name: 🕶️ Nightly Release

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Zon-broken-pipe=kill

jobs:
  release:
    strategy:
      matrix:
        include:
          - name: linux-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: cross
          - name: linux-arm64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            command: cross
          - name: windows-x64
            os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            command: cross
          - name: windows-arm64
            os: windows-latest
            target: aarch64-pc-windows-msvc
            command: cargo
          - name: macos-x64
            os: macos-latest
            target: x86_64-apple-darwin
            command: cargo
          - name: macos-arm64
            os: macos-latest
            target: aarch64-apple-darwin
            command: cargo
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}     
      - name: Install cross
        if: ${{ startsWith(matrix.command, 'cross') }}
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: VS Tools
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: ${{ matrix.command }} build --release --target ${{ matrix.target }}
      - name: Copy
        id: archive
        shell: bash
        run: |
          if [[ "${{ matrix.target }}" =~ "-pc-windows-" ]]; then
              SUFFIX=".exe"
          else
              SUFFIX=""
          fi
          echo "path=target/${{ matrix.target }}/release/s4n$SUFFIX" >> $GITHUB_OUTPUT
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: s4n-${{github.ref_name}}-${{matrix.name}}
          path: |
            ${{ steps.archive.outputs.path }}
